### ISSUE TITLE
encode function crashes

### ISSUE THREAD

**Issue by arre525** [joedf/base64.c#1]
Google directed me to this library, but when trying it it crashed immediately on the encode function.

    unsigned int b64_encode(const unsigned int* in, unsigned int in_len, unsigned char* out) {

    unsigned int i=0, j=0, k=0, s[3];

    for (i=0;i<in_len;i++) {
        s[j++]=*(in+i);
        if (j==3) {
            out[k+0] = b64_chr[ s[0]>>2 ];

b64_chr[ s[0]>>2 ] crashes because s[0] is filled in with potentially a really high number (up to 2^30), and tries to dereference this inside b64_chr.

**Comment by joedf** [comment]
Hmmm interesting... Thank you for reporting this. I had experienced no crash at the time, but it makes sense. Say if I changed `b64_chr[ s[0]>>2 ]` to `b64_chr[ (s[0]&255)>>2 ]`. Would that be a good solution?

**Comment by joedf** [comment]
I have just made a commit, but I did not experience a crash with or without this change. Let know if this seems to be working.
