### ISSUE TITLE
Cant compile

### ISSUE THREAD

**Issue by NaC-L** [joedf/base64.c#2]
I cant compile that test.c file you gave. This is the error :
/tmp/cckwvSUl.o:hello.c:(.text+0x1b8): undefined reference to `b64e_size'
/tmp/cckwvSUl.o:hello.c:(.text+0x1c8): undefined reference to `b64e_size'
/tmp/cckwvSUl.o:hello.c:(.text+0x1d8): undefined reference to `b64e_size'
/tmp/cckwvSUl.o:hello.c:(.text+0x227): undefined reference to `b64_encode'
/tmp/cckwvSUl.o:hello.c:(.text+0x240): undefined reference to `b64_encode'
/tmp/cckwvSUl.o:hello.c:(.text+0x259): undefined reference to `b64_encode'
/tmp/cckwvSUl.o:hello.c:(.text+0x3a7): undefined reference to `b64d_size'
/tmp/cckwvSUl.o:hello.c:(.text+0x3b4): undefined reference to `b64d_size'
/tmp/cckwvSUl.o:hello.c:(.text+0x3c1): undefined reference to `b64d_size'
/tmp/cckwvSUl.o:hello.c:(.text+0x416): undefined reference to `b64_decode'
/tmp/cckwvSUl.o:hello.c:(.text+0x42f): undefined reference to `b64_decode'
/tmp/cckwvSUl.o:hello.c:(.text+0x448): undefined reference to `b64_decode'
/tmp/cckwvSUl.o:hello.c:(.text+0x636): undefined reference to `b64_encodef'
/tmp/cckwvSUl.o:hello.c:(.text+0x78b): undefined reference to `b64_decodef'
collect2: error: ld returned 1 exit status

I am using kali linux mingw-gcc

**Comment by joedf** [comment]
it seems like you didn't include the header file `base64.h` in the same folder.
What command line options did you use?
`gcc test.c base64.c -o test.exe`

**Comment by NaC-L** [comment]
I'm an idiot, i didnt include base64.c to my command, Sorry

**Comment by joedf** [comment]
No issue 👍
