### ISSUE TITLE
Decode base64 to text crash

### ISSUE THREAD

**Issue by simaoferreira24694** [joedf/base64.c#5]
Decode result of "YWRtaW46ODgzNg==" should be "admin:8836"

When I do this
./b64f b YWRtaW46ODgzNg==

The test app crashes

sferreira@sferreira-PC:~/Downloads/base64.c-master/bin$ ./b64f b YWRtaW46ODgzNg==

DECODING from base64 to text
*** Error in `./b64f': free(): invalid next size (fast): 0x00000000010ac420 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f1e964b37e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7f1e964bc37a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f1e964c053c]
./b64f[0x400ae5]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f1e9645c830]
./b64f[0x400749]
======= Memory map: ========
00400000-00402000 r-xp 00000000 08:01 7084656                            /home/sferreira/Downloads/base64.c-master/bin/b64f
00601000-00602000 r--p 00001000 08:01 7084656                            /home/sferreira/Downloads/base64.c-master/bin/b64f
00602000-00603000 rw-p 00002000 08:01 7084656                            /home/sferreira/Downloads/base64.c-master/bin/b64f
010ac000-010cd000 rw-p 00000000 00:00 0                                  [heap]
7f1e90000000-7f1e90021000 rw-p 00000000 00:00 0 
7f1e90021000-7f1e94000000 ---p 00000000 00:00 0 
7f1e96226000-7f1e9623c000 r-xp 00000000 08:01 5509759                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f1e9623c000-7f1e9643b000 ---p 00016000 08:01 5509759                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f1e9643b000-7f1e9643c000 rw-p 00015000 08:01 5509759                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f1e9643c000-7f1e965fc000 r-xp 00000000 08:01 5509721                    /lib/x86_64-linux-gnu/libc-2.23.so
7f1e965fc000-7f1e967fc000 ---p 001c0000 08:01 5509721                    /lib/x86_64-linux-gnu/libc-2.23.so
7f1e967fc000-7f1e96800000 r--p 001c0000 08:01 5509721                    /lib/x86_64-linux-gnu/libc-2.23.so
7f1e96800000-7f1e96802000 rw-p 001c4000 08:01 5509721                    /lib/x86_64-linux-gnu/libc-2.23.so
7f1e96802000-7f1e96806000 rw-p 00000000 00:00 0 
7f1e96806000-7f1e9682c000 r-xp 00000000 08:01 5509693                    /lib/x86_64-linux-gnu/ld-2.23.so
7f1e96a0d000-7f1e96a10000 rw-p 00000000 00:00 0 
7f1e96a2a000-7f1e96a2b000 rw-p 00000000 00:00 0 
7f1e96a2b000-7f1e96a2c000 r--p 00025000 08:01 5509693                    /lib/x86_64-linux-gnu/ld-2.23.so
7f1e96a2c000-7f1e96a2d000 rw-p 00026000 08:01 5509693                    /lib/x86_64-linux-gnu/ld-2.23.so
7f1e96a2d000-7f1e96a2e000 rw-p 00000000 00:00 0 
7ffe93345000-7ffe93366000 rw-p 00000000 00:00 0                          [stack]
7ffe9338a000-7ffe9338d000 r--p 00000000 00:00 0                          [vvar]
7ffe9338d000-7ffe9338f000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Decoded text from base64: aAborted (core dumped)

**Comment by joedf** [comment]
Thanks for reporting this. I'm not sure what I did but it seems that text-mode is broken. Possibly, this error is caused by invalid type choice causing the program to access invalid memory... Perhaps, you could help take me take a look at this? I have not touched C in quite some time, I wrote this mainly as an exercise.

It does not seem to be a semantic error, since the exact same algorithm is used for file-mode, which seems to work flawlessly.
